import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import CrytoContext from "./CrytoContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Crypto-Hunter",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <CrytoContext>
        <Header/>
        {children}</CrytoContext></body>
    </html>
  );
}
